### ISSUE TITLE
fires immediately regardless of time

### ISSUE THREAD

**Issue by jorgyporgy** [forza-panino/Sniper-Bot#1]
Hye when it comes to setting time i am setting time in local time zone in 24 hour format. it is 16 now and the presale is at 13 next day, but it immediately attempts and fails and reverts upon confirming that time. 

  "blockHash": "0x33ed7f9a3ace65d79db5894516eff3b9f809c6a3f5b4f7089011fe21d3a66736",
  "blockNumber": 12261221,
  "contractAddress": null,
  "cumulativeGasUsed": 2400760,
  "from": "0x73ec65017c06e60cc082659fa51f88ee524bfe14",
  "gasUsed": 23684,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x63fc70aec865ef29b9b3fef97d67b5a85b7edfac",
  "transactionHash": "0x58398820ff1f5f2cb075719debc4a9e3ccb099f6872169d381783da72da5a710",
  "transactionIndex": 38,
  "type": "0x0"

**Comment by forza-panino** [comment]
Actually that's the right behaviour:
the starting time is set for the current day,  thus in your case the bot fires immediately  since the trigger time has been passed.
After all, the bot needs to be running the whole time before presales starts, thus it wouldn't be very useful setting the sniper for next day (however, if needed, it's easy to implement)

**Comment by jorgyporgy** [comment]
ahh i see, so this will only work for same day then?

**Comment by forza-panino** [comment]
Yes
I can implement the possibility to set a date, it should be easy and fast, but I don't think it would be useful since you must keep the program running

**Comment by forza-panino** [comment]
I've been thinking about that and actually it would be useful: if a presale starts at 00:00 it would be impossible to snipe it - gonna add the day feature ASAP
