### ISSUE TITLE
every transaction failing

### ISSUE THREAD

**Issue by deeppf** [forza-panino/Sniper-Bot#16]
my every transaction failing..
i am testing on coins which are already launched with presale mode..
but every transaction failing..

this error message just pop up --
Transaction sent successfully.
Transacion hash: 0x18e19f0a9ca57ac494ab5fda208d6530767f5e7af9121253dbaf0e296a76f5a5
Error during transaction execution. Details will follow.
Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x3710fc34b490d33d2fae6b4e19f1e02f7ccffab127bafdd8230e5af98661e416",
  "blockNumber": 13807314,
  "contractAddress": null,
  "cumulativeGasUsed": 13445611,
  "from": "0x44d08848fa71bff4a1282e10a24076f36c79f81e",
  "gasUsed": 21045,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x87be0b856960f57fb0104ef0922cd1dacbd37f64",
  "transactionHash": "0x18e19f0a9ca57ac494ab5fda208d6530767f5e7af9121253dbaf0e296a76f5a5",
  "transactionIndex": 119,
  "type": "0x0"
}
    at Object.TransactionError (C:\Users\DEEP\Desktop\New folder (2)\Sniper-Bot-main\node_modules\web3-core-helpers\lib\errors.js:87:21)
    at Object.TransactionRevertedWithoutReasonError (C:\Users\DEEP\Desktop\New folder (2)\Sniper-Bot-main\node_modules\web3-core-helpers\lib\errors.js:98:21)
    at C:\Users\DEEP\Desktop\New folder (2)\Sniper-Bot-main\node_modules\web3-core-method\lib\index.js:395:57
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  receipt: {
    blockHash: '0x3710fc34b490d33d2fae6b4e19f1e02f7ccffab127bafdd8230e5af98661e416',
    blockNumber: 13807314,
    contractAddress: null,
    cumulativeGasUsed: 13445611,
    from: '0x44d08848fa71bff4a1282e10a24076f36c79f81e',
    gasUsed: 21045,
    logs: [],
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    status: false,
    to: '0x87be0b856960f57fb0104ef0922cd1dacbd37f64',
    transactionHash: '0x18e19f0a9ca57ac494ab5fda208d6530767f5e7af9121253dbaf0e296a76f5a5',
    transactionIndex: 119,
    type: '0x0'
  }
}

C:\Users\DEEP\Desktop\New folder (2)\Sniper-Bot-main>

**Comment by forza-panino** [comment]
That's the right behaviour, presale mode works only with presales
What are you trying will be available in a few days (hope before new year) with the new fairlaunch mode

**Comment by Harjinder-prog** [comment]
will it work on presale sir??
and what should be the gass fee at presale..??
can i use it on pinksale or any other launchpad of bsc??
waiting for ur answer sir..
thanking you..

**Comment by forza-panino** [comment]
At the moment it works with every presale platform where you have to send bnb to the so called "presale address" (i.e. Pinksale, Dxsale, etc.); obviously, in presale mode :)
Gas fee minimum 10
Gas amount I usually put 500000

**Comment by Harjinder-prog** [comment]
sometimes presale starts before the allocated time given.what should we give the time....can we give time befor the launch time??

**Comment by forza-panino** [comment]
In my experience it never happened and I don't think it's possibile: once the timer starts, it's that, it cannot start before

**Comment by Harjinder-prog** [comment]
can i use it on pancakeswap on the day of listing token??
or any other alternative??

**Comment by forza-panino** [comment]
You will be able to do so in a few days with new update :)

**Comment by Harjinder-prog** [comment]
Hei bro can we buy whitlisted presales?

**Comment by forza-panino** [comment]
If the wallet is whitelisted it will work, if not there's no way to bypass launchpad's smart contract restrictions.
