### ISSUE TITLE
[REQ] [is this support  wss:// rpc?]

### ISSUE THREAD

**Issue by kugimiya530** [forza-panino/Sniper-Bot#19]
.. like title

**Comment by forza-panino** [comment]
If I ain't wrong, yes, I should have also tried it myself, just change the line of code for the web3 provider

Furthermore, it's optional, with websocket connection you can subscribe to events on blockchain, thus you could also modify the piece of code that checks for new blocks (the interval) with a subscription - if many people request it I can think of publishing a version with web sockets :)

**Comment by forza-panino** [comment]
@kugimiya530 websocket version is avaliable on websocket-version branch. Cheers :).
