### ISSUE TITLE
Consider switching to yarn instead of npm

### ISSUE THREAD

**Issue by saniales** [forza-panino/Sniper-Bot#5]
it's just faster

**Comment by forza-panino** [comment]
In case of migration to yarn will [this line of code](https://github.com/forza-panino/Sniper-Bot/blob/0ea4fa537c28f16c69fb2809864d3e3ed3da7b22/src/language_pack/selected_language.ts#L4) continue to work or will it need to be substituted with yarn's equivalent (if any)?

**Comment by saniales** [comment]
You should use i18n approach instead of manually using files like this

**Comment by forza-panino** [comment]
Benefits don't overcome probable issues in yarn's installation not straightforward to solve for unexpert users.
